### ISSUE TITLE
add-boilderplate

### ISSUE THREAD

**Issue by plastikfan** [plastikfan/zenobia-ts#1]

**Comment by plastikfan** [comment]
Should I be using webpack-dev-server?

**Comment by plastikfan** [comment]
According to https://stackoverflow.com/questions/29911491/using-webpack-on-server-side-of-nodejs, we might need to use 'commonjs2' as the libraryTarget.

**Comment by plastikfan** [comment]
Still seeing errors assiciated with mocha sidebar:

____________________________________________________________________________
trying to searching for tests using these settings: 

    mocha path: mocha
    test files location: tests/**/spec.ts
    files to ignore: **/.git/**/*,**/node_modules/**/*
    environmets: {}
    requires: ["ts-node/register","source-map-support/register"]
    options:  {}


if you find anything wrong please change those default settings
____________________________________________________________________________
Error: Cannot find module 'ts-node/register'
Require stack:
- /Users/Plastikfan/.vscode/extensions/maty.vscode-mocha-sidebar-0.22.2/lib/worker/findtests.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/Plastikfan/.vscode/extensions/maty.vscode-mocha-sidebar-0.22.2/lib/worker/findtests.js:23:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
Error: Cannot find module 'source-map-support/register'
Require stack:
- /Users/Plastikfan/.vscode/extensions/maty.vscode-mocha-sidebar-0.22.2/lib/worker/findtests.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/Plastikfan/.vscode/extensions/maty.vscode-mocha-sidebar-0.22.2/lib/worker/findtests.js:23:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11

**Comment by plastikfan** [comment]
It turns out that DOM api types come from xmldom-ts (dist/types/types.d.ts) when you include "xmldom-ts" as a dependency and not lib.dom.d.ts as I originballly thought. However, if I remove "dom" from the lib setting in tsconfig, then the types fail to be available at compile time. This is probably because you need to include xmldom-ts.

**Comment by plastikfan** [comment]
On seconds thoughts, I think its probably best to leave in the "dom" in the "lib" tsconfig since xmldom-ts says it brings the dom api to Node js as well as the browser. When you look at the code of xmldom-ts, it links to "dom" via the "lib" setting, which brings the types into compilation scope. When you look at the implementation of xmldom-ts (inside node_modules) you can see implementation classes for dom elements that I assume is the implementation made available to Node.js at runtime.
